### ISSUE TITLE
compactds not included in release tarball file

### ISSUE THREAD

**Issue by thanhleviet** [mourisl/centrifuger#1]
Hi,

Thanks for the excellent tool. Is it possible to include the folder `compactds` in the release tarball as well? This will make creating a `conda` recipe easier.

Thanks
T

**Comment by mourisl** [comment]
Thank you for noticing this issue. I'll check how to make github put the submodules in the release tarball.

**Comment by mourisl** [comment]
It seems github may not support including submodules in the source code tarball. I changed the compactds from submodule to a conventional folder, and the tarball should be fine now.

**Comment by mourisl** [comment]
Thank you!
