### ISSUE TITLE
pre-built index files issue

### ISSUE THREAD

**Issue by Wang-Jing-NZ** [mourisl/centrifuger#14]
We downloaded the pre-compiled index file and tried to run with the files in the example folder. It did not produce expected results, an empty output file. We also tried with our own data, Illumina and ONT, still same empty outputs. We don't see any error messages. Can you get some help on this? Any ideas on the possible cause of this issue? Many thanks.

**Comment by mourisl** [comment]
What was your running command?

**Comment by Wang-Jing-NZ** [comment]
the pre-compile index is the one from Zenodo, https://zenodo.org/records/10023239.
centrifuger 1.0.4 is loaded as a module
the cmd:
module load centrifuger/1.0.4
centrifuger -1 example_1.fq -2 example_2.fq -x /share/databases/centrifuger/db/cfr_hpv+gbsarscov2 > example.tsv
many thanks!

**Comment by mourisl** [comment]
What is the output on the screen, Like finishing load of index? How much memory did you allocate for this job? You may need at least about 50G memory to classify against this database. If it is not the memory issue, can you use centrifuger-inspect (if it is in the module) with --summary to see whether it can read in the index file?

**Comment by Wang-Jing-NZ** [comment]
no, I also tried with reference provided in the example folder and build the index from it. It works. 
centrifuger -1 example_1.fq -2 example_2.fq -x cfr_ref_idx > example_example_index.tsv
[Tue Sep 17 13:13:03 2024] Centrifuger v1.0.4-r153 starts.
[Tue Sep 17 13:13:03 2024] Finishes loading index.
[Tue Sep 17 13:13:03 2024] Inferred --min-hitlen: 23
[Tue Sep 17 13:13:03 2024] Centrifuger finishes.
use the command above, just one line output, 
[Tue Sep 17 13:19:37 2024] Centrifuger v1.0.4-r153 starts.
 -only one line of the output, no msg for loading the index.
 (copied outputs from yersterday's chat with our Linux administrator who has been helped me to get this up running, )

**Comment by mourisl** [comment]
I think the index loading step failed. This could happen due to not enough memory is allocated and the job is killed.

**Comment by Wang-Jing-NZ** [comment]
thank a lot!
we just tried all centrifuger-inspect commands, no outputs from any of the cmd, i.e.,
centrifuger-inspect --summary -x  share/databases/centrifuger/db/cfr_hpv+gbsarscov2 >
how to set memory in centrifuger? Our Linux administrator noticed it in centrifuger-build.Here is a prebuilt index, how do set it when run centrifuger ?

**Comment by mourisl** [comment]
Hmmm, the memory usage should be quite low when running centrifuger-inspect with --summary. So the issue probably is not relate to memory. Can you show me the sizes of the index files you downloaded?

**Comment by Wang-Jing-NZ** [comment]
total 48044504
-rw-r--r-- 1 root root 45035606741 Sep 16 04:55 cfr_hpv+gbsarscov2.1.cfr
-rw-r--r-- 1 root root     5054329 Sep 16 07:37 cfr_hpv+gbsarscov2.2.cfr
-rw-r--r-- 1 root root     1514688 Sep 16 07:37 cfr_hpv+gbsarscov2.3.cfr
 does it help?

**Comment by mourisl** [comment]
The files look fine to me. This is very strange. 

>we just tried all centrifuger-inspect commands, no outputs from any of the cmd, i.e.,
centrifuger-inspect --summary -x share/databases/centrifuger/db/cfr_hpv+gbsarscov2`

The "share/databases/centrifuger/db/cfr_hpv+gbsarscov2" misses a "/" in the beginning. Is it a typo here or a typo when you ran centrifuger-inspect?

**Comment by russellsmithies** [comment]
> gbsarscov2" misses a "/" in the beginning. Is it a typo here or a typo when you ran centrifuger-inspect?

All sorted - we were running it as a conda env inside a singularity container and the wrapper script had a symlink in it that wasn't being followed.

--Russell  (Linux admin)

**Comment by Wang-Jing-NZ** [comment]
oh, a typo, sorry, Not the path I used to run the cmd.

**Comment by Wang-Jing-NZ** [comment]
thank you both for all the help here. Really appreciated!

**Comment by mourisl** [comment]
I'll close this issue for now. Feel free to reopen it or create another thread if you find any issues with Centrifuger.
