### ISSUE TITLE
Only the read1 name appeared in the detailed classified results

### ISSUE THREAD

**Issue by permia** [mourisl/centrifuger#15]
If the inputs are pair reads, only the read1 name appeared in the detailed classified results. Is it nomal results?

Is it possible that a reads is classified and the pair is unclassified?

Or in normal pair-end fastq file, should  the names of read1 and read2 be same?

My code
```
  centrifuger \
  -t "${threads}" \
  -k 1 \
  -1 "${read1}" \
  -2 "${read2}" \
  -x "${index}" \
  2> "${out_dir}"/"${sra_name}"_"${index_name}"_output.log \
  > "${out_dir}"/"${sra_name}"_"${index_name}"_output.tsv
```

My input like this

read1
```
@SRR28892574.1/1 A00289:600:HKWHJDSX2:3:1101:2031:1000 150
NGTTGCTAATTTCAGAATTGTTACCAACTCGGCACCCCTCCAAAACCAGTGTAATTATCTAAGTATCATTTAATTATTAAATAAACAATTTTATTTAAAATAATAAGAAAACGCACTGGTCAGGTAATTCACAAACTATAATCATTCCCC
+
#FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF,F,FFFF,FF:FF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFF:FFFFFF,FFFFFFFFFFFFFFFF
@SRR28892574.2/1 A00289:600:HKWHJDSX2:3:1101:3604:1000 150
NGCGGTGAATGTGCGGAATGACACCACCGCCAGCGATAGTGGCCTTGATCAGCGAGTCCAGCTCCTCATCACCACGGATAGCCAAATGCAAATGGCGCGGAGTAACGCGCTTGACTTTGAGATCCTTTGATGCATTACCGGCCAATTCCA
+
#FFFFF:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF

```

read2

```
@SRR28892574.1/2 A00289:600:HKWHJDSX2:3:1101:2031:1000 150
GGATATTAAATGGTGAATCCTCCATAATAACCCCTCCGTCCTGAAATAATTCCCTCCTTGTTGCGTGTAATTTAGACTATATCTGAACGAGCCTTATAGGGGGAATTAAATTAGGGACCTCTTGTTATTGGACAGGTGTTCACTTGGGGA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF,FFFFFFFFF,FFF,FFFFFFFFFFFFFFFFF:F:FFFFFFF
@SRR28892574.2/2 A00289:600:HKWHJDSX2:3:1101:3604:1000 150
CTCCAATTCCCAGTAGGCCGCATTCACCGCTTCCTGAAGAAGCGTACTACCAGTCACGGCCGTGTGGGCGCCACCGCCGCTGTATACAGTGCTGCCATTTTGGAATACCTCACCGCAGAAGTTTTGGAATTGGCCGGTAATGCATCAAAG
+
FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF:FFF:FFFFFFF:FFFFFFF:FFFFFFFF
```

My output.tsv like this (no read2 name appeared in the result file)
```
readID	seqID	taxID	score	2ndBestScore	hitLength	queryLength	numMatches
SRR28892574.1/1	JAKKPZ010000723.1	166010	3381	0	136	300	1
SRR28892574.2/1	JAKKPZ010000038.1	166010	27920	0	266	300	1

```

**Comment by mourisl** [comment]
In normal paired-end fastq files, the read ID is expected to be the same, except for some suffix like /1/2 or .1.2. Therefore, in general, the read ID from read 1 is sufficient. As you can see the second last column, the number of basepair for this read is 300, which is the sum of the read pairs. This also shows that internally both reads are considered in the classification. Hope this helps.

**Comment by permia** [comment]
Maybe, the header names of the paired reads are usually same. I used odd parameter `--seq-defline '@$ac.$si/$ri $sn $rl'` in fasterq-dump, which made the header name of the paired reads different.

**Comment by mourisl** [comment]
Do you mean if we search the ID "SRR28892574.1" in the fastq file, the "SRR28892574.1/1" and "SRR28892574.1/2" header can not be recognized? Or the "/1" will cause the script to crash?

**Comment by permia** [comment]
> Do you mean if we search the ID "SRR28892574.1" in the fastq file, the "SRR28892574.1/1" and "SRR28892574.1/2" header can not be recognized? Or the "/1" will cause the script to crash?

I guess this problem was caused by BBMap_39.09 not centrifuger. 

If searching the ID "SRR28892574.1" in the fastq file, the "SRR28892574.1/1" and "SRR28892574.1/2" header can only be recognized with `prefix=t`.

If I use `bbmap/filterbyname.sh` without `prefix=t` option to extract the read with the name `SRR28892574.1/1`, no read can be retrieved in both fastq file either in single or pair mode. 

But if I add one more option `prefix=t`, which allow names to match read header prefixes, the reads can be retrieved. However, it's very slow.

So, I delete the /1 in the read name list and  replace the / with whitespace in fastq file. Then I can extract the unclassifed reads efficiently.

```
# extract reads by pair
filterbyname.sh \
in="${read1}" \
in2="${read2}" \
out="${dir}"/"${read1name}"_unclassified_1.fastq \
out2="${dir}"/"${read2name}"_unclassified_2.fastq \
names="${dir}"/unclassified_read_name.txt \
include=t
```

**Comment by mourisl** [comment]
I think I'll make the centrifuger directly remove suffixes like "/1", "/2" automatically in the next version. It looks strange with those suffixes. Another feature on my todo list is to directly output the unclassified reads into fastq files.

**Comment by mourisl** [comment]
Hello, I just pushed a update to the master branch. It the suffixes in the read IDs. I also added two options "--un" and "--cl" to output unclassified and classified reads to the files with specified prefix. For example, when using "--un ${readname}_unclassified", Centrifuger will put unclassified read pairs to "${readname}_unclassified_1.fq.gz" and "${readname}_unclassified_2.fq.gz" files. Please let me know whether this works on your data. If it works, I can draft a new release. Thank you!
