### ISSUE TITLE
filtered due to its short length

### ISSUE THREAD

**Issue by yi1873** [mourisl/centrifuger#3]
How to retain sequences below 1000bp in centrifuger-build?
Especially for the viral sequences, it is best to preserve those that are above 500 bp.

**Comment by yi1873** [comment]
Yes, some abnormal intervals have already been masked.

**Comment by yi1873** [comment]
Now there is another question I want to ask: Approximately how long does it take to build a centrifuger index with 200Gbp of data?  I have already submitted the task to run for 16 hours, and it's still not finished.

**Comment by mourisl** [comment]
That could take a few days. How many threads do you give it, and how much memory do you have?

**Comment by yi1873** [comment]
16 threads  and 500G memory

**Comment by mourisl** [comment]
Then you may try to run centrifuger-build with the option "-t 16 --build-mem 400G", which might make it faster in the end. Nevertheless, I think it will still take a few days. This is one of the drawbacks of FM index :(..

**Comment by mourisl** [comment]
Hi @yi1873 , just want to follow up on the progress of the indexing building. Is it still running? Does it output something like extract XXX chunks?
