### ISSUE TITLE
Is it possible to output only number of bases with exact match? 

### ISSUE THREAD

**Issue by rahulvrane** [mourisl/centrifuger#4]
In the output atm, it indicates an approx number of bases that matched a ref sequence. I am keen to tighten this a bit and only have exact match lengths reported.. is that possible? I couldn't see any parameter that indicates 'exact match' or number of mismatches..

Thanks a ton
Cheers
Rahul

**Comment by mourisl** [comment]
This is the exact match lengths identified in Centrifuger. However, Centrifuger does not search for maximal matches, so the actual match length to a ref could be slightly larger. Hope this helps.
