### ISSUE TITLE
Is centrifuger suitable for metatrancriptomic data?

### ISSUE THREAD

**Issue by permia** [mourisl/centrifuger#5]

**Comment by mourisl** [comment]
The algorithm should support metatranscriptomic data to the DNA/nucleotide-based database. There are other approaches for metatranscriptomic data like mapping to the amino-acid-based database. Our current indexing strategy only supports "ACGT" character, but we will extend to amino acid sequences in future versions.

**Comment by permia** [comment]
> The algorithm should support metatranscriptomic data to the DNA/nucleotide-based database. There are other approaches for metatranscriptomic data like mapping to the amino-acid-based database. Our current indexing strategy only supports "ACGT" character, but we will extend to amino acid sequences in future versions. Hope this helps.

Thanks a lot. Does it mean that centrifuger could properly assign reads from spliced transcript to the genome?

How to get the nodes.dmp, names.dmp and ref_seqid.map file when build custom database index

`../centrifuger-build -r ref.fa --taxonomy-tree nodes.dmp --name-table names.dmp --conversion-table ref_seqid.map -o cfr_ref_idx`

**Comment by mourisl** [comment]
> Does it mean that centrifuger could properly assign reads from spliced transcript to the genome?

Yes. Ideally, Centrifuger will found a mismatch around the splice site, and resume the finding for the next exon to the genome after skipping one base pair.

> How to get the nodes.dmp, names.dmp and ref_seqid.map file when build custom database index

You can use "centrifuger-download taxonomy" to download nodes.dmp and names.dmp files from NCBI.  For the ref_seqid.map file, you may need to run "centrifuger-download [database_you_like] > ref_seqid.map". Essentially, the ref_seqid.map maps each sequence ID in the fasta file to the taxonomy ID. More details can be found in https://ccb.jhu.edu/software/centrifuge/manual.shtml#database-download-and-index-building .
