### ISSUE TITLE
how to install using pthreads under Linux (ubuntu 24.04)

### ISSUE THREAD

**Issue by koppk** [mourisl/centrifuger#7]
Could you please explain how to install centrifuger using pthreads? Thanks

**Comment by mourisl** [comment]
I think pthreads comes with the LInux release. What is the error message you received when running "make" in Centrifuger folder?

**Comment by koppk** [comment]
Hi, thanks. No error message but plenty of warnings during make. Please, see attached file.
[make_stdout.txt](https://github.com/mourisl/centrifuger/files/15300899/make_stdout.txt)

**Comment by koppk** [comment]
This did the trick:
1. install the respective ubuntu 24.04 package
sudo apt-get install libpthread-stubs0-dev
2. then run make in the centrifuger folder.

**Comment by mourisl** [comment]
Those warning messages should be fine. I did not get warnings on our server, but this is probably a gcc version thing. I saw those warnings on the github action. I will clean those up in the next release (or just change the gcc warning flags).
